apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-web-template
  title: AWS Web Application
  description: Crear aplicación web en AWS con S3 y CloudFront
  tags:
    - recommended
    - aws
    - web
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Información del Proyecto
      required:
        - name
        - description
      properties:
        name:
          title: Nombre
          type: string
          pattern: '^[a-zA-Z0-9-]+$'
        description:
          title: Descripción
          type: string
        region:
          title: Región AWS
          type: string
          default: us-east-1
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
  steps:
    - id: template
      name: Crear Archivos
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          region: ${{ parameters.region }}
    - id: publish
      name: Publicar
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=giovanemere&repo=${{ parameters.name }}
    - id: register
      name: Registrar
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repositorio
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Catálogo
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
