apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - aws
    - generated
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
